### PR TITLE
add swap file from died vi session to gitignore

### PR DESCRIPTION
**Pull request by mschlech**

### CODE REVIEW

**Review by matthiasbernhardt — CHANGES_REQUESTED** [review]
Does it happen frequently that your vim crashes and wouldn't you rather remove the stale file or save & quit vim before committing? I take this as a non-serious test, but if that really improves your workflow, I will reconsider to approve and merge it.

**Comment by mschlech** [comment]
as i can handle this, it is from a community contribution perspective not bad to avoid useless artefacts within this repository. just in case someone from outside cannot handle this. Just a proposal. but good to know to be more precise in the commit / pull request comments.

**Comment by matthiasbernhardt** [comment]
I'm not sure if this prevents community from active participation. We did not have a single case of a contribution that accidentally submitted swap files. But where should we start and stop? Do we have to include `.DS_Store` because Apple users tend to check that in? Do we have to include files ending in `*.bak` or `*~`? And shouldn't that be in the settings of Vim users or Apple users rather than in the repository, that knows little about the preferred tools of contributors? If so, we should compile a list of best practice gitignore entries rather than listing this one selectively.

**Comment by matthiasbernhardt** [comment]
As we agreed in personal talk, we consider this pull request as a test. I close it now.

**Pull request closed without merging**
